name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    container: node:14-alpine

    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          REACT_APP_API_URL: http://191.101.18.67:3000
          REACT_APP_JWT_SECRET: ${{ secrets.REACT_APP_JWT_SECRET }}
        run: |
          npm install
          npm run build
      - name: Firebase deploy
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
